baseurl         = "/"
theme           = "iris"
languageCode    = "en-US"
title           = "Hugo Iris"
canonifyurls    = true

[params]
  googleAnalytics = ""
  author          = "peaceiris"
  description     = "Demo slides for Hugo Iris"
  custom_css      = ["remark.css", "custom.css"]
  highlightStyle  = "solarized-light" # Another recommended styles are "monokai" and "rainbow".
  mathjax         = true
  mermaid         = true
